import {
  account,
  accountRelations,
  cohort,
  cohort_member,
  cohort_memberRelations,
  cohortRelations,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
  scimProvider,
  scimProviderRelations,
  session,
  sessionRelations,
  ssoProvider,
  ssoProviderRelations,
  user,
  userRelations,
  verification,
} from "./auth";

const schema = {
  account,
  accountRelations,
  cohort,
  cohortRelations,
  cohort_member,
  cohort_memberRelations,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
  scimProvider,
  scimProviderRelations,
  session,
  sessionRelations,
  ssoProvider,
  ssoProviderRelations,
  user,
  userRelations,
  verification,
};

export { schema };
