import {
  account,
  accountRelations,
  cohort,
  cohortRelations,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
  session,
  sessionRelations,
  teamMember,
  teamMemberRelations,
  user,
  userRelations,
  verification,
} from "./auth";

const schema = {
  account,
  accountRelations,
  cohort,
  cohortRelations,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationRelations,
  session,
  sessionRelations,
  teamMember,
  teamMemberRelations,
  user,
  userRelations,
  verification,
};

export { schema };
